# Importing Libraries and Functions

In [39]:
# Import libraries
import kagglehub
import pandas as pd
import numpy as np

import sys
from pathlib import Path

# Import functions from src/features.py
sys.path.append(
    str(Path().resolve().parent)
)

from src.features import (
    get_match_result,
    goal_diff,
    add_position_group,
    squad_rating
)

# Load Data

In [40]:
# Load Cleaned Datasets
results = pd.read_csv("../data/processed/results_clean.csv")
wc2026_draw = pd.read_csv("../data/processed/wc2026_draw_clean.csv")
players = pd.read_csv("../data/processed/players_clean.csv")
elo_ratings = pd.read_csv("../data/processed/elo_clean.csv")

In [41]:
results["date"] = pd.to_datetime(results["date"])
elo_ratings["rank_date"] = pd.to_datetime(elo_ratings["rank_date"])

# Features
## 1. Team Ratings

The average rating of the 26 person squad for each country.

In [42]:
# Generate team ratings and verifying the output
team_ratings = squad_rating(players).sort_values(["squad_size", "squad_rating"], ascending=[False, False])
team_ratings

                   country  squad_rating  squad_size  missing_players
0                   France     84.230769          26                0
3                  England     84.076923          26                0
1                    Spain     83.730769          26                0
4                   Brazil     83.615385          26                0
8                  Germany     83.576923          26                0
6                Argentina     83.038462          26                0
10                Portugal     83.000000          26                0
7              Netherlands     81.730769          26                0
5                  Belgium     79.884615          26                0
11                 Uruguay     78.269231          26                0
12             Switzerland     77.846154          26                0
14                 Croatia     77.846154          26                0
16                 Austria     77.538462          26                0
15                  Turkey     76.961538          26                0
21                Colombia     76.846154          26                0
20                 Morocco     76.500000          26                0
31                   Japan     75.807692          26                0
2                   Norway     75.730769          26                0
17                  Sweden     75.692308          26                0
22                 Senegal     75.615385          26                0
29          Czech Republic     75.538462          26                0
23           United States     75.461538          26                0
19                Scotland     75.269231          26                0
18                 Algeria     74.615385          26                0
28                   Ghana     74.192308          26                0
13             South Korea     73.846154          26                0
24                 Ecuador     73.461538          26                0
36                Paraguay     73.346154          26                0
26  Bosnia and Herzegovina     72.576923          26                0
34                DR Congo     71.807692          26                0
25                  Canada     71.500000          26                0
37               Australia     70.615385          26                0
33            Saudi Arabia     70.000000          26                0
38             New Zealand     66.961538          26                0
27             Ivory Coast     75.461538          25                1
32                 Tunisia     67.230769          23                3
30                  Mexico     67.692308          22                4
40              Cape Verde     62.923077          18                8
42            South Africa     56.807692          14               12
41                  Panama     57.923077          11               15
45                 Curaçao     56.076923          10               16
44                   Haiti     55.769231           9               17
46                    Iraq     54.769231           9               17
35                    Iran     56.346154           8               18
9                    Egypt     56.192308           6               20
43              Uzbekistan     52.923077           4               22
39                  Jordan     51.423077           2               24
47                   Qatar     50.000000           0               26

## 2. Elo Features

In [43]:
# Sorting by date for good measure, though it should already be sorted
elo_ratings = elo_ratings.sort_values("rank_date")
results = results.sort_values("date")

# Home team Elo ratings
home_elo = elo_ratings.rename(columns={
    "country_full": "home_team",
    "total_points": "home_elo"
})
# Merge home team Elo ratings with results
results = pd.merge_asof(
    results.sort_values("date"),
    home_elo.sort_values("rank_date"),
    left_on="date",
    right_on="rank_date",
    by="home_team",
    direction="backward"
)

# Away team Elo ratings
away_elo = elo_ratings.rename(columns={
    "country_full": "away_team",
    "total_points": "away_elo"
})

# Merge away team Elo ratings with results
results = pd.merge_asof(
    results.sort_values("date"),
    away_elo.sort_values("rank_date"),
    left_on="date",
    right_on="rank_date",
    by="away_team",
    direction="backward"
)

1. elo_diff feature

The difference in elo rating between home and away teams at the time of each match.

In [44]:
results["elo_diff"] = results["home_elo"] - results["away_elo"]

2. home_higher_elo feature

If the home_team has a higher elo rating than the away team, the value is 1. Else, 0.

In [45]:
results["home_higher_elo"] = (results["home_elo"] > results["away_elo"]).astype(int)

In [46]:
results[["date", "home_team", "away_team", "home_elo", "away_elo", "elo_diff", "home_higher_elo"]].sample(10)

,date,home_team,away_team,home_elo,away_elo,elo_diff,home_higher_elo
47577,2024-09-09,Puerto Rico,Aruba,NaN,NaN,NaN,0
33787,2010-05-27,South Africa,Colombia,392.0,776.0,-384.0,0
7147,1967-10-01,Russia,Switzerland,NaN,NaN,NaN,0
37108,2013-07-25,Japan,Australia,689.0,671.0,18.0,1
48836,2025-11-13,Armenia,Hungary,NaN,NaN,NaN,0
20756,1995-12-16,Thailand,Vietnam,NaN,NaN,NaN,0
4167,1955-11-06,Netherlands,Norway,NaN,NaN,NaN,0
42488,2019-06-07,Georgia,Gibraltar,NaN,NaN,NaN,0
40768,2017-06-28,Seychelles,Mozambique,NaN,NaN,NaN,0
38575,2015-03-30,Qatar,Slovenia,300.0,NaN,NaN,0

In [49]:
with pd.option_context('display.max_seq_items', None):
    print(results["away_team"].unique())

<StringArray>
[                         'England',                         'Scotland',
                            'Wales',                 'Northern Ireland',
                           'Canada',                        'Argentina',
                          'Hungary',                   'Czechoslovakia',
                          'Austria',                          'Uruguay',
                           'France',                      'Switzerland',
                         'Alderney',                         'Guernsey',
                      'Netherlands',                          'Belgium',
              'Trinidad and Tobago',                           'Jersey',
                          'Germany',                           'Norway',
                          'Denmark',                           'Sweden',
                            'Italy',                            'Chile',
                        'Catalonia',                          'Finland',
                           'Russia',                         'China PR',
                       'Luxembourg',                           'Brazil',
                   'Basque Country',                      'Philippines',
                    'United States',                          'Romania',
                           'Greece',                       'Yugoslavia',
                            'Egypt',                            'Spain',
                          'Estonia',                           'Guyana',
                         'Provence',                            'Japan',
                      'El Salvador',                       'Costa Rica',
                         'Paraguay',                           'Poland',
                         'Portugal',                        'Australia',
                    'Central Spain',                           'Mexico',
                          'Galicia',                         'Brittany',
                         'Asturias',                      'New Zealand',
                           'Latvia',                        'Guatemala',
                          'Curaçao',                         'Bulgaria',
                           'Turkey',                        'Lithuania',
              'Republic of Ireland',                     'South Africa',
                          'Jamaica',                           'Uganda',
                          'Bolivia',                            'Haiti',
                            'Kenya',                          'Ukraine',
                         'Honduras',                        'Nicaragua',
                             'Peru',                            'Aruba',
                       'Martinique',                         'Barbados',
                             'Cuba',                           'Israel',
                        'Indonesia',                         'Suriname',
                      'Saint Lucia',                         'Colombia',
                        'Venezuela',                          'Ecuador',
                          'Grenada',                            'India',
                           'Panama',                         'Slovakia',
                          'Croatia',                          'Lebanon',
                        'Manchukuo',                      'Puerto Rico',
                             'Iran',                       'Guadeloupe',
                         'Mongolia',                         'Tanzania',
                           'Zambia',                       'Montenegro',
                        'Mauritius',                         'Zimbabwe',
                    'French Guiana',                          'Réunion',
                          'Albania',                         'Zanzibar',
                         'Ethiopia',                       'Madagascar',
                         'Dominica',                      'South Korea',
                         'Djibouti',               'Dominican Republic',
                           'Cyprus',                          'Iceland',
                          'Nigeria',                            'Syria',
                         'DR Congo',                           'Serbia',
                           'Taiwan',                      'Afghanistan',
                          'Myanmar',                          'Vanuatu',
                            'Ghana',                         'Pakistan',
                        'German DR',                     'Sierra Leone',
                    'Guinea-Bissau',                           'Gambia',
                         'Saarland',                           'Tahiti',
                          'Burundi',                         'Cameroon',
                        'Sri Lanka',                          'Vietnam',
                        'Hong Kong',                        'Singapore',
                         'Thailand',                    'New Caledonia',
                         'Cambodia',                         'Malaysia',
                 'Vietnam Republic',                       'Kyrgyzstan',
                          'Belarus',                          'Moldova',
                    'North Vietnam',                             'Togo',
                      'North Korea',                            'Sudan',
                            'Libya',                            'Malta',
                            'Benin',                       'Cape Verde',
                            'Gabon',         'Central African Republic',
                     'Burkina Faso',                             'Mali',
                      'Ivory Coast',                            'Congo',
                             'Iraq',                          'Tunisia',
                          'Morocco', 'Saint Vincent and the Grenadines',
                             'Laos',                       'Mauritania',
                          'Liberia',                            'Niger',
                          'Senegal',                           'Guinea',
                           'Malawi',                           'Jordan',
                           'Kuwait',                             'Chad',
                 'Papua New Guinea',                  'Solomon Islands',
                          'Somalia',                     'Saudi Arabia',
                          'Algeria',                          'Bermuda',
                        'Palestine',                            'Yemen',
                          'Bahrain',                             'Oman',
        'Wallis Islands and Futuna',                          'Corsica',
                'Western Australia',                         'Botswana',
                             'Fiji',                         'Eswatini',
                            'Qatar',                          'Lesotho',
                          'Bahamas',                           'Brunei',
                     'Cook Islands',                        'Yemen DPR',
             'United Arab Emirates',                    'Faroe Islands',
                            'Nepal',              'Antigua and Barbuda',
                       'Bangladesh',                       'Seychelles',
                'Equatorial Guinea',                       'Mozambique',
                           'Angola',            'São Tomé and Príncipe',
                            'Macau',            'Saint Kitts and Nevis',
                          'Armenia',                       'Kazakhstan',
                          'Comoros',                         'Maldives',
                            'Tonga',                         'Kiribati',
                           'Tuvalu',                            'Samoa',
                        'Greenland',                  'Northern Cyprus',
                           'Rwanda',                    'Liechtenstein',
                           'Bhutan',                      'South Yemen',
                   'American Samoa',                   'Cayman Islands',
           'British Virgin Islands',                     'Sint Maarten',
                         'Ynys Môn',                         'Shetland',
                    'Åland Islands',                     'Saint Martin',
                       'San Marino',                       'Montserrat',
                         'Anguilla',                    'Isle of Wight',
                          'Georgia',                             'Guam',
                     'Turkmenistan',                         'Slovenia',
                       'Uzbekistan',                          'Eritrea',
                       'Tajikistan',                          'Namibia',
                       'Azerbaijan',                      'Isle of Man',
                        'Gibraltar',                  'North Macedonia',
                   'Czech Republic',                           'Belize',
           'Bosnia and Herzegovina',                          'Andorra',
                            'Hitra',                            'Frøya',
         'Northern Mariana Islands',                           'Kernow',
         'Turks and Caicos Islands',     'United States Virgin Islands',
                       'Micronesia',                     'Saare County',
                           'Rhodes',                           'Monaco',
                            'Tibet',                           'Orkney',
                 'Falkland Islands',                          'Mayotte',
                     'Vatican City',                      'Timor-Leste',
                             'Sark',                          'Gotland',
                          'Sealand',                         'Chechnya',
                        'Occitania',                        'Ambazonia',
                    'Western Isles',                           'Crimea',
                            'Sápmi',                          'Menorca',
                  'Iraqi Kurdistan',                          'Padania',
                 'Arameans Suryoye',                             'Gozo',
                     'Two Sicilies',                 'Saint Barthélemy',
        'Saint Pierre and Miquelon',                          'Bonaire',
                    'Romani people',                           'Raetia',
                          'Cilento',                   'Chagos Islands',
                   'Western Sahara',                           'Darfur',
                      'Tamil Eelam',                          'Artsakh',
                         'Abkhazia',                      'South Sudan',
                        'Andalusia',                    'South Ossetia',
                   'County of Nice',                     'Ellan Vannin',
                       'Luhansk PR',                       'Donetsk PR',
                         'Felvidék',                           'Panjab',
                        'Franconia',                       'Somaliland',
                     'Székely Land',                  'Western Armenia',
                           'Kosovo',                       'Kárpátalja',
          'United Koreans in Japan',                        'Yorkshire',
                           'Surrey',                          'Kabylia',
                     'Matabeleland',                         'Cascadia',
                           'Barawa',               'Parishes of Jersey',
                         'Chameria',                     'Saint Helena',
                           'Biafra',                        'Maule Sur',
                           'Aymara',                            'Hmong',
                           'Ticino',                 'Marshall Islands']
Length: 318, dtype: str